# GNOME keyboard shortcuts
# host=h97hd3  gnome=46.0  date=2026-09-04T11:10:26+02:00
# restore with: dconf load /org/gnome/ < gnome-shortcuts.ini

[desktop/wm/keybindings]
maximize=@as []
move-to-monitor-down=['<Control><Super>3']
move-to-monitor-left=['<Control><Super>1']
move-to-monitor-right=['<Control><Super>2']
move-to-workspace-last=['<Shift><Super>End']
move-to-workspace-left=['<Shift><Super>Left']
move-to-workspace-right=['<Shift><Super>Right']
raise-or-lower=['<Control><Super>Down']
switch-applications=['<Alt>Tab']
switch-applications-backward=['<Shift><Alt>Tab']
switch-to-workspace-left=['<Control>Left']
switch-to-workspace-right=['<Control>Right']
switch-windows=['<Super>Tab']
switch-windows-backward=['<Shift><Super>Tab']
toggle-maximized=['<Control><Super>Up']
unmaximize=@as []

[mutter/keybindings]
toggle-tiled-left=['<Control><Super>Left']
toggle-tiled-right=['<Control><Super>Right']

[shell/keybindings]
open-new-window-application-1=@as []
open-new-window-application-2=@as []
open-new-window-application-3=@as []
toggle-overview=['<Control>Down']

